[package]
name = "crypto_pipe"
version = "0.4.3"
authors = ["KizzyCode Software Labs./Keziah Biermann"]
build = "build.rs"

[dependencies]
asn1_der = "0.5.2"
etrace = "0.2.7"
cli = { git = "https://github.com/KizzyCode/cli" }